### ISSUE TITLE
Failed to migrate

### ISSUE THREAD

**Issue by spacemeowx2** [BeatLeader/beatleader-server#2]
https://www.beatleader.xyz/u/3528/beatleader/date/1
https://www.beatleader.xyz/u/76561198090195655

* login using steam
* logout
* signup in game
* login signuped account
* migrate steam account
* HTTP STATUS 500

Now I get two accounts, desync. How to solve it?

**Comment by NSGolova** [comment]
Probably fixed, try one more time, please.

**Comment by spacemeowx2** [comment]
Successfully synced! Thanks for the fix!
