### ISSUE TITLE
Failed to migrate

### ISSUE THREAD

**Issue by WGzeyu** [BeatLeader/beatleader-server#3]
https://www.beatleader.xyz/u/143/beatleader/date/1
https://www.beatleader.xyz/u/76561198174192501

I tried the migrate yesterday and had the same problem as #2 , tried again today and had a different problem.
As of yesterday, I had both accounts with the correct avatar and region.
Today I tried the following:

- login using BL account
- click`Migrate to Steam`
- login using Steam account

At this point, the `Migrate` button in the top navigation bar disappeared, and the account currently logged in on the BL are also switched to the Steam account, which were still two separate accounts.
After that I changed my browser and tried the above process again, the problem remained, but then I reopened my personal page and there was a problem with the BL page of my Steam account, first the region changed, a little later the avatar changed, and finally even the ID changed together.
I'm pretty sure it's not that I opened someone else's personal page by mistake, this is the page that opened after clicking `Me`.
Incidentally, the URL of my ScoreSaber personal page is as follows, the ID in the URL is the same, the information in ScoreSaber is completely correct, compared to BL page is simply two very different people.
`https://scoresaber.com/u/76561198174192501`

**Comment by NSGolova** [comment]
Fixed account and migrated scores🤔
