### ISSUE TITLE
modifiedScore doesn't take into account modifiers

### ISSUE THREAD

**Issue by nanikit** [BeatLeader/beatleader-server#44]
baseScore and modifiedScore of records having FS, NF modifier are same.

![image](https://github.com/BeatLeader/beatleader-server/assets/45276129/4fe94233-73fd-4503-822c-1c16684f19b5)

Scoresaber doesn't. Is it intended?

**Comment by NSGolova** [comment]
Yes, this is the intended behavior for maps that give PP. Modifiers change star rating instead of the score for them

**Comment by nanikit** [comment]
OK, then I should change my mod code.
