### ISSUE TITLE
Can't use API due to CORS denial

### ISSUE THREAD

**Issue by nanikit** [BeatLeader/beatleader-server#7]
I want to use beatleader pfp for my overlay, but it couldn't be acquired directly by user ID.

So I tried fetch in web page but it was also blocked by the CORS policy.

Can it be allowed?

**Comment by NSGolova** [comment]
Yeah, send the url you will access the API from

**Comment by nanikit** [comment]
For your test? I can't provide one because I can't see it works.

If you will manage this as allow list, I'll make server handler for bypassing this.

**Comment by nanikit** [comment]
If you want to test, I think typing `await fetch('https://api.beatleader.xyz/api/player/...')` in any other site's developer console would be sufficient.

**Comment by NSGolova** [comment]
I meant the website from which you will access the API. So I can just add you to the list. I can't use a wildcard `*` here in order for "Access-Control-Allow-Credentials" to work.

**Comment by DziugasRam** [comment]
Maybe it could just be allowed for all websites?

**Comment by nanikit** [comment]
My website is added to allowlist, so close this.
